# Generated by Django 5.1.3 on 2024-11-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
